using System;
using Windows.System;
using SilkInput = Silk.NET.Input;

namespace ProGPU.Uno;

public static class UnoInputBridge
{
    public static SilkInput.Key TranslateKey(VirtualKey key)
    {
        return key switch
        {
            VirtualKey.None => SilkInput.Key.Unknown,
            VirtualKey.A => SilkInput.Key.A,
            VirtualKey.B => SilkInput.Key.B,
            VirtualKey.C => SilkInput.Key.C,
            VirtualKey.D => SilkInput.Key.D,
            VirtualKey.E => SilkInput.Key.E,
            VirtualKey.F => SilkInput.Key.F,
            VirtualKey.G => SilkInput.Key.G,
            VirtualKey.H => SilkInput.Key.H,
            VirtualKey.I => SilkInput.Key.I,
            VirtualKey.J => SilkInput.Key.J,
            VirtualKey.K => SilkInput.Key.K,
            VirtualKey.L => SilkInput.Key.L,
            VirtualKey.M => SilkInput.Key.M,
            VirtualKey.N => SilkInput.Key.N,
            VirtualKey.O => SilkInput.Key.O,
            VirtualKey.P => SilkInput.Key.P,
            VirtualKey.Q => SilkInput.Key.Q,
            VirtualKey.R => SilkInput.Key.R,
            VirtualKey.S => SilkInput.Key.S,
            VirtualKey.T => SilkInput.Key.T,
            VirtualKey.U => SilkInput.Key.U,
            VirtualKey.V => SilkInput.Key.V,
            VirtualKey.W => SilkInput.Key.W,
            VirtualKey.X => SilkInput.Key.X,
            VirtualKey.Y => SilkInput.Key.Y,
            VirtualKey.Z => SilkInput.Key.Z,
            VirtualKey.Number0 => SilkInput.Key.Number0,
            VirtualKey.Number1 => SilkInput.Key.Number1,
            VirtualKey.Number2 => SilkInput.Key.Number2,
            VirtualKey.Number3 => SilkInput.Key.Number3,
            VirtualKey.Number4 => SilkInput.Key.Number4,
            VirtualKey.Number5 => SilkInput.Key.Number5,
            VirtualKey.Number6 => SilkInput.Key.Number6,
            VirtualKey.Number7 => SilkInput.Key.Number7,
            VirtualKey.Number8 => SilkInput.Key.Number8,
            VirtualKey.Number9 => SilkInput.Key.Number9,
            VirtualKey.NumberPad0 => SilkInput.Key.Keypad0,
            VirtualKey.NumberPad1 => SilkInput.Key.Keypad1,
            VirtualKey.NumberPad2 => SilkInput.Key.Keypad2,
            VirtualKey.NumberPad3 => SilkInput.Key.Keypad3,
            VirtualKey.NumberPad4 => SilkInput.Key.Keypad4,
            VirtualKey.NumberPad5 => SilkInput.Key.Keypad5,
            VirtualKey.NumberPad6 => SilkInput.Key.Keypad6,
            VirtualKey.NumberPad7 => SilkInput.Key.Keypad7,
            VirtualKey.NumberPad8 => SilkInput.Key.Keypad8,
            VirtualKey.NumberPad9 => SilkInput.Key.Keypad9,
            VirtualKey.F1 => SilkInput.Key.F1,
            VirtualKey.F2 => SilkInput.Key.F2,
            VirtualKey.F3 => SilkInput.Key.F3,
            VirtualKey.F4 => SilkInput.Key.F4,
            VirtualKey.F5 => SilkInput.Key.F5,
            VirtualKey.F6 => SilkInput.Key.F6,
            VirtualKey.F7 => SilkInput.Key.F7,
            VirtualKey.F8 => SilkInput.Key.F8,
            VirtualKey.F9 => SilkInput.Key.F9,
            VirtualKey.F10 => SilkInput.Key.F10,
            VirtualKey.F11 => SilkInput.Key.F11,
            VirtualKey.F12 => SilkInput.Key.F12,
            VirtualKey.Up => SilkInput.Key.Up,
            VirtualKey.Down => SilkInput.Key.Down,
            VirtualKey.Left => SilkInput.Key.Left,
            VirtualKey.Right => SilkInput.Key.Right,
            VirtualKey.Enter => SilkInput.Key.Enter,
            VirtualKey.Escape => SilkInput.Key.Escape,
            VirtualKey.Tab => SilkInput.Key.Tab,
            VirtualKey.Space => SilkInput.Key.Space,
            VirtualKey.Back => SilkInput.Key.Backspace,
            VirtualKey.Delete => SilkInput.Key.Delete,
            VirtualKey.Insert => SilkInput.Key.Insert,
            VirtualKey.Home => SilkInput.Key.Home,
            VirtualKey.End => SilkInput.Key.End,
            VirtualKey.PageUp => SilkInput.Key.PageUp,
            VirtualKey.PageDown => SilkInput.Key.PageDown,
            VirtualKey.Shift => SilkInput.Key.ShiftLeft,
            VirtualKey.Control => SilkInput.Key.ControlLeft,
            VirtualKey.Menu => SilkInput.Key.AltLeft,
            VirtualKey.LeftWindows => SilkInput.Key.SuperLeft,
            VirtualKey.RightWindows => SilkInput.Key.SuperRight,
            _ => SilkInput.Key.Unknown
        };
    }
}
