namespace ProGPU.WinUI.Designer;

using System;
using System.Text;
using System.Collections.Generic;
using Microsoft.UI.Xaml;
using Microsoft.UI.Xaml.Controls;
using Microsoft.UI.Xaml.Documents;
using ProGPU.Vector;
using ProGPU.Layout;
using ProGPU.Scene;

public static class DesignerSerializer
{
    private static readonly HashSet<string> Keywords = new HashSet<string>(StringComparer.Ordinal)
    {
        "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char", "checked", "class", "const",
        "continue", "decimal", "default", "delegate", "do", "double", "else", "enum", "event", "explicit",
        "extern", "false", "finally", "fixed", "float", "for", "foreach", "goto", "if", "implicit", "in",
        "int", "interface", "internal", "is", "lock", "long", "namespace", "new", "null", "object", "operator",
        "out", "override", "params", "private", "protected", "public", "readonly", "ref", "return", "sbyte",
        "sealed", "short", "sizeof", "stackalloc", "static", "string", "struct", "switch", "this", "throw",
        "true", "try", "typeof", "uint", "ulong", "unchecked", "unsafe", "ushort", "using", "virtual", "void",
        "volatile", "while"
    };

    public static string SerializeToCSharp(Canvas canvas, bool isResponsiveMode = false)
    {
        if (canvas == null) return "";

        var sb = new StringBuilder();
        sb.AppendLine("// Generated by ProGPU Visual Designer C# Script Generator");
        sb.AppendLine("// Local Time: " + DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss"));
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using Microsoft.UI.Xaml;");
        sb.AppendLine("using Microsoft.UI.Xaml.Controls;");
        sb.AppendLine("using Microsoft.UI.Xaml.Documents;");
        sb.AppendLine("using ProGPU.Vector;");
        sb.AppendLine("using ProGPU.Layout;");
        sb.AppendLine("using System.Numerics;");
        sb.AppendLine();
        sb.AppendLine("public static class VisualTreeFactory");
        sb.AppendLine("{");
        sb.AppendLine("    public static Canvas CreateVisualTree()");
        sb.AppendLine("    {");
        sb.AppendLine("        var rootCanvas = new Canvas");
        sb.AppendLine("        {");
        
        float rootWidth = float.IsNaN(canvas.Width) ? (canvas.Size.X > 0 ? canvas.Size.X : 800f) : canvas.Width;
        float rootHeight = float.IsNaN(canvas.Height) ? (canvas.Size.Y > 0 ? canvas.Size.Y : 600f) : canvas.Height;
        sb.AppendLine($"            Width = {FormatFloat(rootWidth)}f,");
        sb.AppendLine($"            Height = {FormatFloat(rootHeight)}f");
        sb.AppendLine("        };");
        sb.AppendLine();

        int varCounter = 1;
        var declaredNames = new HashSet<string>();

        foreach (var child in canvas.Children)
        {
            if (child is FrameworkElement childFe)
            {
                var childVar = SerializeElement(childFe, ref varCounter, declaredNames, sb, 2, isResponsiveMode);
                sb.AppendLine($"        rootCanvas.Children.Add({childVar});");
                sb.AppendLine();
            }
        }

        sb.AppendLine("        return rootCanvas;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string SerializeElement(FrameworkElement element, ref int varCounter, HashSet<string> declaredNames, StringBuilder sb, int indentLevel, bool isResponsiveMode)
    {
        var typeName = element.GetType().Name;
        
        // Clean and unique variable name
        string rawName;
        if (string.IsNullOrEmpty(element.Name))
        {
            rawName = typeName.ToLower();
        }
        else
        {
            var sbClean = new StringBuilder();
            foreach (char c in element.Name)
            {
                if (char.IsLetterOrDigit(c) || c == '_')
                {
                    sbClean.Append(c);
                }
                else
                {
                    sbClean.Append('_');
                }
            }
            rawName = sbClean.ToString();
        }

        if (string.IsNullOrEmpty(rawName))
        {
            rawName = typeName.ToLower();
        }
        else if (char.IsDigit(rawName[0]))
        {
            rawName = "var_" + rawName;
        }

        if (Keywords.Contains(rawName))
        {
            rawName = "var_" + rawName;
        }

        string varName = rawName;
        int suffix = 1;
        while (declaredNames.Contains(varName))
        {
            varName = $"{rawName}_{suffix++}";
        }
        declaredNames.Add(varName);

        var indent = new string(' ', indentLevel * 4);
        sb.AppendLine($"{indent}var {varName} = new {typeName}");
        sb.AppendLine($"{indent}{{");

        // Write standard properties
        if (!string.IsNullOrEmpty(element.Name))
        {
            sb.AppendLine($"{indent}    Name = \"{EscapeStringLiteral(element.Name)}\",");
        }

        float width = float.IsNaN(element.Width) ? element.Size.X : element.Width;
        float height = float.IsNaN(element.Height) ? element.Size.Y : element.Height;
        if (width <= 0) width = 120f;
        if (height <= 0) height = 36f;

        sb.AppendLine($"{indent}    Width = {FormatFloat(width)}f,");
        sb.AppendLine($"{indent}    Height = {FormatFloat(height)}f,");

        if (element.Opacity != 1.0f)
        {
            sb.AppendLine($"{indent}    Opacity = {FormatFloat(element.Opacity)}f,");
        }

        if (element.Rotation != 0f)
        {
            sb.AppendLine($"{indent}    Rotation = {FormatFloat(element.Rotation)}f,");
        }

        if (element.RenderTransformOrigin != new System.Numerics.Vector2(0.5f, 0.5f))
        {
            sb.AppendLine($"{indent}    RenderTransformOrigin = new System.Numerics.Vector2({FormatFloat(element.RenderTransformOrigin.X)}f, {FormatFloat(element.RenderTransformOrigin.Y)}f),");
        }

        // Margin & Padding
        var margin = element.Margin;
        if (margin.Left != 0 || margin.Top != 0 || margin.Right != 0 || margin.Bottom != 0)
        {
            sb.AppendLine($"{indent}    Margin = new Microsoft.UI.Xaml.Thickness({FormatFloat(margin.Left)}f, {FormatFloat(margin.Top)}f, {FormatFloat(margin.Right)}f, {FormatFloat(margin.Bottom)}f),");
        }

        var padding = element.Padding;
        if (padding.Left != 0 || padding.Top != 0 || padding.Right != 0 || padding.Bottom != 0)
        {
            sb.AppendLine($"{indent}    Padding = new Microsoft.UI.Xaml.Thickness({FormatFloat(padding.Left)}f, {FormatFloat(padding.Top)}f, {FormatFloat(padding.Right)}f, {FormatFloat(padding.Bottom)}f),");
        }

        // Background / BorderBrush / CornerRadius etc.
        if (TryGetDependencyValue<float>(element, "CornerRadius", out var fcr) && fcr != 0f)
        {
            sb.AppendLine($"{indent}    CornerRadius = {FormatFloat(fcr)}f,");
        }

        if (TryGetDependencyValue<Brush>(element, "Background", out var bg))
        {
            if (bg is ThemeResourceBrush trb)
            {
                sb.AppendLine($"{indent}    Background = new ThemeResourceBrush(\"{trb.ResourceKey}\"),");
            }
            else if (bg is SolidColorBrush scb)
            {
                var c = scb.Color;
                sb.AppendLine($"{indent}    Background = new SolidColorBrush(new Vector4({FormatFloat(c.X)}f, {FormatFloat(c.Y)}f, {FormatFloat(c.Z)}f, {FormatFloat(c.W)}f)),");
            }
        }

        if (TryGetDependencyValue<Brush>(element, "BorderBrush", out var bb))
        {
            if (bb is ThemeResourceBrush trb)
            {
                sb.AppendLine($"{indent}    BorderBrush = new ThemeResourceBrush(\"{trb.ResourceKey}\"),");
            }
            else if (bb is SolidColorBrush scb)
            {
                var c = scb.Color;
                sb.AppendLine($"{indent}    BorderBrush = new SolidColorBrush(new Vector4({FormatFloat(c.X)}f, {FormatFloat(c.Y)}f, {FormatFloat(c.Z)}f, {FormatFloat(c.W)}f)),");
            }
        }

        if (TryGetDependencyValue<Thickness>(element, "BorderThickness", out var t) &&
            (t.Left != 0 || t.Top != 0 || t.Right != 0 || t.Bottom != 0))
        {
            sb.AppendLine($"{indent}    BorderThickness = new Microsoft.UI.Xaml.Thickness({FormatFloat(t.Left)}f, {FormatFloat(t.Top)}f, {FormatFloat(t.Right)}f, {FormatFloat(t.Bottom)}f),");
        }

        // Horizontal and Vertical Alignment
        sb.AppendLine($"{indent}    HorizontalAlignment = Microsoft.UI.Xaml.HorizontalAlignment.{element.HorizontalAlignment},");
        sb.AppendLine($"{indent}    VerticalAlignment = Microsoft.UI.Xaml.VerticalAlignment.{element.VerticalAlignment},");

        // Slider / Progress specific properties
        if (TryGetFloatValue(element, "Value", out var value))
        {
            sb.AppendLine($"{indent}    Value = {FormatFloat(value)}f,");
        }

        if (TryGetFloatValue(element, "Minimum", out var minimum))
        {
            sb.AppendLine($"{indent}    Minimum = {FormatFloat(minimum)}f,");
        }

        if (TryGetFloatValue(element, "Maximum", out var maximum))
        {
            sb.AppendLine($"{indent}    Maximum = {FormatFloat(maximum)}f,");
        }

        if (TryGetDependencyValue<bool>(element, "IsChecked", out var isChecked))
        {
            sb.AppendLine($"{indent}    IsChecked = {(isChecked ? "true" : "false")},");
        }

        if (TryGetDependencyValue<bool>(element, "IsOn", out var isOn))
        {
            sb.AppendLine($"{indent}    IsOn = {(isOn ? "true" : "false")},");
        }

        if (TryGetText(element, out var txt) && !string.IsNullOrEmpty(txt))
        {
            sb.AppendLine($"{indent}    Text = \"{EscapeStringLiteral(txt)}\",");
        }

        if (TryGetPlaceholderText(element, out var placeholder) && !string.IsNullOrEmpty(placeholder))
        {
            sb.AppendLine($"{indent}    PlaceholderText = \"{EscapeStringLiteral(placeholder)}\",");
        }

        if (element is PasswordBox passwordBox && !string.IsNullOrEmpty(passwordBox.Password))
        {
            sb.AppendLine($"{indent}    Password = \"{EscapeStringLiteral(passwordBox.Password)}\",");
        }

        if (TryGetFontSize(element, out var fontSize))
        {
            sb.AppendLine($"{indent}    FontSize = {FormatFloat(fontSize)}f,");
        }

        // Panel orientation
        if (element is Microsoft.UI.Xaml.Controls.StackPanel stackPanel)
        {
            sb.AppendLine($"{indent}    Orientation = Orientation.{stackPanel.Orientation},");
        }
        else if (element is WrapPanel wrapPanel)
        {
            sb.AppendLine($"{indent}    Orientation = Orientation.{wrapPanel.Orientation},");
        }

        // WrapPanel specific properties
        if (element is WrapPanel wrapFe)
        {
            if (!float.IsNaN(wrapFe.ItemWidth))
            {
                sb.AppendLine($"{indent}    ItemWidth = {FormatFloat(wrapFe.ItemWidth)}f,");
            }
            if (!float.IsNaN(wrapFe.ItemHeight))
            {
                sb.AppendLine($"{indent}    ItemHeight = {FormatFloat(wrapFe.ItemHeight)}f,");
            }
            if (wrapFe.HorizontalSpacing != 0f)
            {
                sb.AppendLine($"{indent}    HorizontalSpacing = {FormatFloat(wrapFe.HorizontalSpacing)}f,");
            }
            if (wrapFe.VerticalSpacing != 0f)
            {
                sb.AppendLine($"{indent}    VerticalSpacing = {FormatFloat(wrapFe.VerticalSpacing)}f,");
            }
        }

        // DockPanel specific properties
        if (element is DockPanel dockFe)
        {
            if (!dockFe.LastChildFill)
            {
                sb.AppendLine($"{indent}    LastChildFill = false,");
            }
        }

        sb.AppendLine($"{indent}}};");

        // Grid Definition Serialization
        if (element is Grid gridFe)
        {
            foreach (var colDef in gridFe.ColumnDefinitions)
            {
                if (colDef.UnitType == GridUnitType.Auto)
                    sb.AppendLine($"{indent}{varName}.ColumnDefinitions.Add(GridLength.Auto);");
                else if (colDef.UnitType == GridUnitType.Star)
                    sb.AppendLine($"{indent}{varName}.ColumnDefinitions.Add(GridLength.Star({FormatFloat(colDef.Value)}f));");
                else
                    sb.AppendLine($"{indent}{varName}.ColumnDefinitions.Add(new GridLength({FormatFloat(colDef.Value)}f, GridUnitType.Absolute));");
            }

            foreach (var rowDef in gridFe.RowDefinitions)
            {
                if (rowDef.UnitType == GridUnitType.Auto)
                    sb.AppendLine($"{indent}{varName}.RowDefinitions.Add(GridLength.Auto);");
                else if (rowDef.UnitType == GridUnitType.Star)
                    sb.AppendLine($"{indent}{varName}.RowDefinitions.Add(GridLength.Star({FormatFloat(rowDef.Value)}f));");
                else
                    sb.AppendLine($"{indent}{varName}.RowDefinitions.Add(new GridLength({FormatFloat(rowDef.Value)}f, GridUnitType.Absolute));");
            }
        }

        // Set Attached properties
        if (!isResponsiveMode)
        {
            float left = Canvas.GetLeft(element);
            float top = Canvas.GetTop(element);
            if (left != 0)
            {
                sb.AppendLine($"{indent}Canvas.SetLeft({varName}, {FormatFloat(left)}f);");
            }
            if (top != 0)
            {
                sb.AppendLine($"{indent}Canvas.SetTop({varName}, {FormatFloat(top)}f);");
            }
        }

        int row = Microsoft.UI.Xaml.Controls.Grid.GetRow(element);
        if (row != 0)
        {
            sb.AppendLine($"{indent}Grid.SetRow({varName}, {row});");
        }

        int col = Microsoft.UI.Xaml.Controls.Grid.GetColumn(element);
        if (col != 0)
        {
            sb.AppendLine($"{indent}Grid.SetColumn({varName}, {col});");
        }

        // Attached Dock properties if element's parent is DockPanel
        if (element.Parent is DockPanel)
        {
            var dock = DockPanel.GetDock(element);
            if (dock != Dock.Left)
            {
                sb.AppendLine($"{indent}DockPanel.SetDock({varName}, Dock.{dock});");
            }
        }

        // Content/Children recursion and association
        if (element is SplitView splitView)
        {
            if (splitView.Pane is FrameworkElement paneFe)
            {
                var paneVar = SerializeElement(paneFe, ref varCounter, declaredNames, sb, indentLevel, isResponsiveMode);
                sb.AppendLine($"{indent}{varName}.Pane = {paneVar};");
            }

            if (splitView.Content is FrameworkElement contentFe)
            {
                var contentVar = SerializeElement(contentFe, ref varCounter, declaredNames, sb, indentLevel, isResponsiveMode);
                sb.AppendLine($"{indent}{varName}.Content = {contentVar};");
            }
        }
        else if (element is ContentControl contentControl)
        {
            var contentVal = contentControl.Content;
            if (contentVal is RichTextBlock rtb)
            {
                string rtbBase = $"{varName}_content_text";
                string rtbName = rtbBase;
                int rtbSuffix = 1;
                while (declaredNames.Contains(rtbName))
                {
                    rtbName = $"{rtbBase}_{rtbSuffix++}";
                }
                declaredNames.Add(rtbName);

                sb.AppendLine($"{indent}var {rtbName} = new RichTextBlock();");
                foreach (var inline in rtb.Inlines)
                {
                    if (inline is Run run)
                    {
                        sb.AppendLine($"{indent}{rtbName}.Inlines.Add(new Run(\"{EscapeStringLiteral(run.Text)}\"));");
                    }
                }
                sb.AppendLine($"{indent}{varName}.Content = {rtbName};");
            }
            else if (contentVal is FrameworkElement contentFe)
            {
                var contentVar = SerializeElement(contentFe, ref varCounter, declaredNames, sb, indentLevel, isResponsiveMode);
                sb.AppendLine($"{indent}{varName}.Content = {contentVar};");
            }
            else if (contentVal != null)
            {
                string s = contentVal.ToString() ?? "";
                sb.AppendLine($"{indent}{varName}.Content = \"{EscapeStringLiteral(s)}\";");
            }
        }

        // Border Child
        if (element is Border { Child: FrameworkElement childFe })
        {
            var childVar = SerializeElement(childFe, ref varCounter, declaredNames, sb, indentLevel, isResponsiveMode);
            sb.AppendLine($"{indent}{varName}.Child = {childVar};");
        }

        // Panel Children
        if (element is Panel panel && panel.Children.Count > 0)
        {
            foreach (var childNode in panel.Children)
            {
                if (childNode is FrameworkElement panelChildFe)
                {
                    var childVar = SerializeElement(panelChildFe, ref varCounter, declaredNames, sb, indentLevel, isResponsiveMode);
                    sb.AppendLine($"{indent}{varName}.Children.Add({childVar});");
                }
            }
        }

        return varName;
    }

    private static bool TryGetDependencyValue<T>(FrameworkElement element, string name, out T value)
    {
        value = default!;
        var dependencyProperty = DependencyProperty.Lookup(element.GetType(), name);
        if (dependencyProperty == null ||
            (!typeof(T).IsAssignableFrom(dependencyProperty.PropertyType) && dependencyProperty.PropertyType != typeof(T)))
        {
            return false;
        }

        var currentValue = element.GetValue(dependencyProperty);
        if (currentValue is T typedValue)
        {
            value = typedValue;
            return true;
        }

        return false;
    }

    private static bool TryGetFloatValue(FrameworkElement element, string name, out float value)
    {
        if (TryGetDependencyValue<float>(element, name, out value))
        {
            return true;
        }

        switch (name)
        {
            case "Value" when element is ProgressBar progressBar:
                value = progressBar.Value;
                return true;
            case "Minimum" when element is ProgressBar progressBar:
                value = progressBar.Minimum;
                return true;
            case "Maximum" when element is ProgressBar progressBar:
                value = progressBar.Maximum;
                return true;
            default:
                value = default;
                return false;
        }
    }

    private static bool TryGetText(FrameworkElement element, out string? text)
    {
        switch (element)
        {
            case TextBox textBox:
                text = textBox.Text;
                return true;
            case TextBlock textBlock:
                text = textBlock.Text;
                return true;
            case RichTextBlock richTextBlock:
                text = GetInlineText(richTextBlock.Inlines);
                return true;
            default:
                if (TryGetDependencyValue<string>(element, "Text", out var dependencyText))
                {
                    text = dependencyText;
                    return true;
                }

                text = null;
                return false;
        }
    }

    private static string GetInlineText(IEnumerable<Inline> inlines)
    {
        var sb = new StringBuilder();
        foreach (var inline in inlines)
        {
            AppendInlineText(sb, inline);
        }

        return sb.ToString();
    }

    private static void AppendInlineText(StringBuilder sb, Inline inline)
    {
        switch (inline)
        {
            case Run run:
                sb.Append(run.Text);
                break;
            case LineBreak:
                sb.AppendLine();
                break;
            case Span span:
                foreach (var child in span.Inlines)
                {
                    AppendInlineText(sb, child);
                }
                break;
        }
    }

    private static bool TryGetPlaceholderText(FrameworkElement element, out string? placeholderText)
    {
        switch (element)
        {
            case TextBox textBox:
                placeholderText = textBox.PlaceholderText;
                return true;
            case ComboBox comboBox:
                placeholderText = comboBox.PlaceholderText;
                return true;
            case PasswordBox passwordBox:
                placeholderText = passwordBox.PlaceholderText;
                return true;
            default:
                if (TryGetDependencyValue<string>(element, "PlaceholderText", out var dependencyPlaceholder))
                {
                    placeholderText = dependencyPlaceholder;
                    return true;
                }

                placeholderText = null;
                return false;
        }
    }

    private static bool TryGetFontSize(FrameworkElement element, out float fontSize)
    {
        switch (element)
        {
            case TextBox textBox:
                fontSize = textBox.FontSize;
                return true;
            case PasswordBox passwordBox:
                fontSize = passwordBox.FontSize;
                return true;
            case ComboBox comboBox:
                fontSize = comboBox.FontSize;
                return true;
            case DataGrid dataGrid:
                fontSize = dataGrid.FontSize;
                return true;
            case RichTextBlock richTextBlock:
                fontSize = richTextBlock.FontSize;
                return true;
            case FontIcon fontIcon:
                fontSize = fontIcon.FontSize;
                return true;
            case FlowDocument flowDocument:
                fontSize = flowDocument.FontSize;
                return true;
            case MarkdownTextBlock markdownTextBlock:
                fontSize = markdownTextBlock.FontSize;
                return true;
            default:
                return TryGetDependencyValue<float>(element, "FontSize", out fontSize);
        }
    }

    private static string EscapeStringLiteral(string? s)
    {
        if (s == null) return "";
        return s.Replace("\\", "\\\\")
                .Replace("\"", "\\\"")
                .Replace("\r", "\\r")
                .Replace("\n", "\\n")
                .Replace("\t", "\\t");
    }

    private static string FormatFloat(float value)
    {
        return value.ToString("G", System.Globalization.CultureInfo.InvariantCulture);
    }
}
